CREATE TABLE IF NOT EXISTS today_items (
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS work_items (
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL
);

